name: Root-Conf S3 Deploy

on:
  workflow_call:
    inputs:
      CI_ENV:
        required: true
        type: string
      CONTENTFUL_ENVIRONMENT:
        required: true
        type: string
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
      AWS_DEFAULT_REGION:
        required: true
      AWS_SESSION_TOKEN:
        required: true
      S3_ORIGIN_BUCKET:
        required: true
      SONAR_TOKEN:
        required: true        
      SLACK_WEBHOOK_URL:
        required: true 

jobs:

  Testing:
    runs-on: ubuntu-latest
    steps:
      - name: Code checkout 
        uses: actions/checkout@v4
        with:
          fetch-depth: 5

      - name: Instalar Node.js y npm
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build app
        run: rm -rf ./out && npm run build
        shell: bash

      - name: Setup SonarQube
        uses: warchant/setup-sonar-scanner@v7

#    Run sonar-scanner test
      - name: SonarQube Scan
        run: sonar-scanner -X
              -Dproject.settings=./.github/sonar/sonar-project.properties
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Revisar archivos 
        run: tree & ls -lath

      
      - name: SonarQube Quality Gate check
        id: sonarqube-quality-gate-check
        uses: sonarsource/sonarqube-quality-gate-action@master
        timeout-minutes: 5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Slack Notification
        uses: act10ns/slack@v1
        with: 
          status: ${{ job.status }}
          steps: ${{toJson(steps)}}
          channel: '#proyecto-ort'
          message: Proyecto-Frontend ${{ github.job}} en ${{ inputs.CI_ENV }} branch fue ${{ job.status }} \n
        if: always() 
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      

  FUNTIONAL_TESTING:
    needs:  Testing
    runs-on: ubuntu-latest
    steps:
      - name: Code checkout 
        uses: actions/checkout@v4
        with:
          fetch-depth: 5

      - name: Instalar Node.js y npm
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build app
        run: rm -rf ./out && npm run build
        shell: bash

      - name: Install NGINX
        run: |
          sudo apt-get update
          sudo apt-get install nginx -y

      - name: Copy Files to NGINX Folder
        run: |
          sudo rm -fr /var/www/html/*
          sudo cp -r dist/* /var/www/html/

      - name: Restart NGINX Service
        run: sudo systemctl restart nginx

      - name: Instalar Newman
        run: |
              npm install -g newman@latest
              npm install -g newman-reporter-htmlextra

      - name: Ejecutar pruebas funcionales con Newman
        run: |
              newman run ./.github/Postman/collection.json -r cli,htmlextra --reporter-htmlextra-export testArtifacts/htmlreport.html
      - name: Revisar archivos 
        run: tree
                    
      - name: Almacenar reporte como artefacto
        id: upload_artifact
        uses: actions/upload-artifact@v3
        with:
          name: reporte-postman-root-conf-${{ inputs.CI_ENV }}
          path: ./testArtifacts

      - name: Slack Notification
        uses: act10ns/slack@v1
        with: 
          status: ${{ job.status }}
          steps: ${{toJson(steps)}}
          channel: '#proyecto-ort'
          message: Proyecto-Frontend ${{ github.job}} en ${{ inputs.CI_ENV }} branch fue ${{ job.status }} \n
        if: always() 
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}



  Build_and_Deploy:
    needs:  FUNTIONAL_TESTING
    runs-on: ubuntu-latest
    steps:
      - name: Code checkout 
        uses: actions/checkout@v4
        with:
          fetch-depth: 5

      - name: Instalar Node.js y npm
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build app
        run: rm -rf ./out && npm run build
        shell: bash

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
          aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{secrets.AWS_DEFAULT_REGION}}

      - name: S3 Deploy
        run: aws s3 sync dist/ s3://$S3_ORIGIN_BUCKET
        shell: bash
        env:
          S3_ORIGIN_BUCKET: ${{ secrets.S3_ORIGIN_BUCKET }}
          
      - name: Slack Notification
        uses: act10ns/slack@v1
        with: 
          status: ${{ job.status }}
          steps: ${{toJson(steps)}}
          channel: '#proyecto-ort'
          message: Proyecto-Frontend ${{ github.job}} en ${{ inputs.CI_ENV }} branch fue ${{ job.status }} \n
        if: always() 
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}      